# Generated by Django 4.2 on 2023-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, verbose_name='Product Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('rupees', models.IntegerField(verbose_name='Rupees')),
            ],
        ),
    ]
